# Generate compile_commands.txt for kernel compilation
# Educational tool showing exact slangc commands for manual reproduction

# Find all compiled kernels and their metadata
file(GLOB KERNEL_METADATA ${KERNEL_OUTPUT_DIR}/*.json)

set(COMPILE_COMMANDS "# SLANG Kernel Compilation Commands
# Copy-paste these commands to manually reproduce kernel compilation
# Generated by Kerntopia build system

")

foreach(METADATA_FILE ${KERNEL_METADATA})
    file(READ ${METADATA_FILE} METADATA_JSON)
    
    # Extract command from JSON (simplified parsing for now)
    string(REGEX MATCH "\"manual_compilation\": \"([^\"]+)\"" MATCH_RESULT ${METADATA_JSON})
    if(CMAKE_MATCH_1)
        string(APPEND COMPILE_COMMANDS "${CMAKE_MATCH_1}\n")
    endif()
endforeach()

string(APPEND COMPILE_COMMANDS "
# Notes:
# - Commands assume slangc is in PATH
# - Source files are relative to project root
# - Output files go to build/kernels/
# - All kernels compiled during build for consistency
")

# Write compile commands file
file(WRITE ${KERNEL_OUTPUT_DIR}/compile_commands.txt "${COMPILE_COMMANDS}")
message(STATUS "Generated compile_commands.txt for educational use")